config/routes.rb
Rails.application.routes.draw do
  root to: 'room#index'

  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/topics', to: 'users#showtopics', as: 'user_topics'
  get '/users/:id/messages', to: 'users#showmessage', as: 'user_message'
  get '/users/:id/sendmessages', to: 'users#showsendmessage', as: 'user_message_send'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch "/users/:id", to: "users#update"

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  post '/search', to: 'search#search', as:'search'
  get '/search/:search', to: 'search#show', as: 'search_result'

  # get '/messages', to: 'message#index'
  post '/messages', to: 'message#create'
  patch '/users/:id/messages/destroy/send/:id', to: 'message#notshowsendmessage', as: 'message_notshow_send'
  patch '/users/:id/messages/destroy/receive/:id', to: 'message#notshowreceivemessage', as: 'message_notshow_receive'

  get '/rooms', to: 'room#index'
  get '/rooms/new', to: 'room#new'
  post '/rooms', to: 'room#create'
  get '/rooms/:id', to: 'room#show', as: 'room'
  get '/rooms/:id/edit', to: 'room#edit', as: 'edit_room'
  patch '/rooms/:id', to: 'room#update'
  delete '/rooms/destroy/:id', to: 'room#destroy', as: 'room_destroy'

  # get '/rooms/:id', to: 'topics#index'
  post '/rooms/:id', to: 'topics#create'
  get '/rooms/:id/topics/:id', to: 'topics#show', as: 'topic'
  get '/rooms/:id/topics/:id/edit', to: 'topics#edit', as: 'edit_topic'
  patch "/rooms/:id/topics/:id", to: "topics#update"
  delete '/rooms/:id/topics/destroy/:id', to: 'topics#destroy', as: 'topic_destroy'

  post '/rooms/:id/topics/:id', to: 'comments#create'
  get '/comments/:id', to: 'comments#show', as: 'comment'
  get '/comments/:id/edit', to: 'comments#edit', as: 'edit_comment'
  patch "/comments/:id", to: "comments#update"
  delete '/comments/destroy/:id', to: 'comments#destroy', as: 'comment_destroy'

end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true, length: {minimum: 4, maximum: 30}
  validates :content, presence: true, length: {maximum: 10000}
  belongs_to :user
  belongs_to :room
  has_many :comments, dependent: :destroy
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
    if current_user == nil
      @user = User.new
    else
      @user = current_user
    end
  end

  def new
    @topic = Topic.new
  end

  def create
    @room = Room.find_by_id(params[:id])
    @topic = Topic.new(topic_params)
    @topic.owner_id = current_user.id.to_s
    @topic.owner_name = current_user.username
    current_user.topics << @topic
    if @topic.save
      redirect_to room_path(@topic.room_id)
    else
      flash[:alert] = @topic.errors.full_messages.join(' ')
      redirect_to room_path(@topic.room_id)
    end
  end

  def show
    if current_user == nil
      @user = User.new
    else
      @user = current_user
    end
    @topic = Topic.find_by_id(params[:id])
    @comments = @topic.comments
    @room = Room.find_by_id(@topic.room_id)
  end

  def edit
    if current_user == nil
      @user = User.new
    else
      @user = current_user
    end

    @topic = Topic.find_by_id(params[:id])
    if (current_user.id.to_s != @topic.owner_id)
      flash[:error] = 'Stop Hacking!'
      redirect_to '/'
    end
  end

  def update
    @topic = Topic.find_by_id(params[:id])
    @topic.update_attributes(topic_params)
    if @topic.save
      redirect_to @topic
    end
  end

  def destroy
    @topic = Topic.find_by_id(params[:id])
    @topic.destroy
    flash[:notice] = "#{@topic.title} has been deleted"
    redirect_to room_path(@topic.room_id)
  end


  private

  def topic_params
    params.require(:topic).permit(:title, :content, :room_id)
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.erb
<div class="container">
<%= form_for @topic do |f| %>
  <div class="">
    <h1>Title:</h1>
    <%= f.text_field :title %>
  </div>
  <div class="">
    <p style= "margin-top:1%;">Content:</p>
    <%= f.text_area :content, style: "width:80%; height:30vh;" %>
  </div>
  <%= f.submit "Save", style: "margin-top:1%" %>
<% end %>
</div>

app/views/topics/index.html.erb
<div class="container">
  <div class="sessionHeaderBox">

    <div class="sessionHeader">
      <img class="sessionLogo" src='<%=image_path("sessionLogo.png")%>' alt="">

      <div class="sessionSearchBar">
        <span class="sessionName">SessionName</span>
        <br>
        <br>
        <div id="custom-search-input sessionSearch">
              <div class="input-group">
                  <input type="text" class="  search-query form-control" placeholder="Search" />
                  <span class="input-group-btn">
                      <button class="btn btn-danger" type="button">
                          <span class=" glyphicon glyphicon-search"></span>
                      </button>
                  </span>
              </div>
          </div>
      </div>

    </div>

    <span class="helper"></span>

  </div>

  <div class="topicsContainer">
    <% @topics.each do |topic| %>
    <%= link_to url_for(action: 'show', controller: 'topics', id: "#{topic.id}") do %>
    <div class="topicBox">
      <h1 class="topicTitle"><%= topic.title %></h1>
      <br>
      <p class="topicContent"><%= topic.content %></p>
      <p class="float-right">Created By: <%= topic.owner_name %></p>
    </div>

    <% end %>
    <% end %>
  </div>
  <% if current_user != nil%>
  <%= form_with scope: :topic, url: "/topics" do |f| %>
    <div>
      <%= f.text_field :title, placeholder: "Title" %>
    </div>
    <div>
      <%= f.text_area :content, placeholder: "Content" %>
    </div>

    <%= f.submit %>
  <% end %>
  <% end %>

</div>

app/views/topics/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to "#{@room.name}", room_path(@room.id) %></li>
  </ol>
  <table style="width:100%">
    <tr class="floor">
      <td class="authorBox">
        <%= link_to user_path(@topic.owner_id) do %>
        <img src="<%= asset_path("gameIcon.png") %>" class="gameHeadIcon">
          <h1><%= @topic.owner_name %></h1>
        <% end %>
      </td>
      <td class="contentBox">
        <h1><%= @topic.title %></h1>
        <p><%= @topic.content%>
        <% if @user.id.to_s === @topic.owner_id %>
          <%= link_to topic_destroy_path(@topic, :id => @topic.id), controller: 'topics', action: 'destroy', method: :delete, data: {confirm: 'Delete this topic?'}, :class => "toolBTN float-right" do %>
            <span class="glyphicon glyphicon-trash" title = "Delete topic"> </span>
          <% end %>
          <%= link_to edit_topic_path(@topic, :id => @topic.id), controller: 'topics', action: 'get', :class => "toolBTN float-right" do %>
            <span class="glyphicon glyphicon-pencil" title = "Edit topic"> </span>
          <% end %>
        <% end %>
        </p>
      </td>
    </tr>
  </table>

  <% @comments.sort.each do |comment|%>
  <table style="width:100%">
    <tr class="floor">
      <td class="authorBox">
        <%= link_to user_path(comment.owner_id) do %>
        <img src="<%= asset_path("gameIcon.png") %>" class="gameHeadIcon">
        <h1><%= comment.owner_name%></h1>
        <%end%>
      </td>
      <td class="contentBox">
        <p><%= comment.content%>
          <% if @user.id.to_s === comment.owner_id %>
            <%= link_to comment_destroy_path(comment, :id => comment.id), controller: 'comments', action: 'destroy', method: :delete, data: {confirm: 'Delete this comment?'}, :class => "toolBTN float-right" do %>
              <span class="glyphicon glyphicon-trash" title = "Delete comment"> </span>
            <% end %>
            <%= link_to edit_comment_path(comment, :id => comment.id), controller: 'comments', action: 'get', :class => "toolBTN float-right" do %>
              <span class="glyphicon glyphicon-pencil" title = "Edit comment"> </span>
            <% end %>
          <% end %>
        </p>
      </td>
    </tr>
  </table>
  <% end %>

  <% if current_user != nil%>
    <%= form_with scope: :comment, url: "comments" do |f| %>

      <div>
        <%= f.text_area :content, placeholder: "Content", style: "width:80%; height:30vh; opacity:.9; margin-top:3%;" %>
      </div>
      <div>
        <%= f.hidden_field :topic_id, :value => "#{@topic.id}"%>
      </div>

    <%= f.submit :class => " btn btn-default" %>
    <% end %>
  <% end %>


</div>