config/routes.rb
Rails.application.routes.draw do
  root to: 'room#index'

  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/topics', to: 'users#showtopics', as: 'user_topics'
  get '/users/:id/messages', to: 'users#showmessage', as: 'user_message'
  get '/users/:id/sendmessages', to: 'users#showsendmessage', as: 'user_message_send'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch "/users/:id", to: "users#update"

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  post '/search', to: 'search#search', as:'search'
  get '/search/:search', to: 'search#show', as: 'search_result'

  # get '/messages', to: 'message#index'
  post '/messages', to: 'message#create'
  patch '/users/:id/messages/destroy/send/:id', to: 'message#notshowsendmessage', as: 'message_notshow_send'
  patch '/users/:id/messages/destroy/receive/:id', to: 'message#notshowreceivemessage', as: 'message_notshow_receive'

  get '/rooms', to: 'room#index'
  get '/rooms/new', to: 'room#new'
  post '/rooms', to: 'room#create'
  get '/rooms/:id', to: 'room#show', as: 'room'
  get '/rooms/:id/edit', to: 'room#edit', as: 'edit_room'
  patch '/rooms/:id', to: 'room#update'
  delete '/rooms/destroy/:id', to: 'room#destroy', as: 'room_destroy'

  # get '/rooms/:id', to: 'topics#index'
  post '/rooms/:id', to: 'topics#create'
  get '/rooms/:id/topics/:id', to: 'topics#show', as: 'topic'
  get '/rooms/:id/topics/:id/edit', to: 'topics#edit', as: 'edit_topic'
  patch "/rooms/:id/topics/:id", to: "topics#update"
  delete '/rooms/:id/topics/destroy/:id', to: 'topics#destroy', as: 'topic_destroy'

  post '/rooms/:id/topics/:id', to: 'comments#create'
  get '/comments/:id', to: 'comments#show', as: 'comment'
  get '/comments/:id/edit', to: 'comments#edit', as: 'edit_comment'
  patch "/comments/:id", to: "comments#update"
  delete '/comments/destroy/:id', to: 'comments#destroy', as: 'comment_destroy'

end

app/models/room.rb
class Room < ApplicationRecord
  has_many :topics, dependent: :destroy
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  def index
    if current_user == nil
      @user = User.new
    else
      @user = current_user
    end
    @rooms = Room.all
    @room = Room.find_by_id(params[:id])
  end

  def new
    if current_user == nil
      @user = User.new
    else
      @user = current_user
    end
    @room = Room.new
  end

  def create
    if current_user == nil
      @user = User.new
    else
      @user = current_user
    end
    @room = Room.create(room_params)
    redirect_to rooms_path
  end

  def show
    if current_user == nil
      @user = User.new
    else
      @user = current_user
    end
    @room = Room.find_by_id(params[:id])
    @topics = @room.topics
  end

  def edit
    if current_user == nil
      @user = User.new
    else
      @user = current_user
    end
    @room = Room.find_by_id(params[:id])
  end

  def update
    @room = Room.find_by_id(params[:id])
    @room.update_attributes(params.require(:room).permit(:name, :description, :icon))
    if @room.save
      redirect_to '/'
    end
  end

  def destroy
    @room = Room.find_by_id(params[:id])
    @room.destroy
    redirect_to '/'
  end

  private

  def room_params
    params.require(:room).permit(:name, :description)
  end
end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/room/edit.html.erb
<div class="container">
  <%= form_for @room do |r| %>
    <div class="">
      <h1>Name:</h1>
      <%= r.text_field :name %>
    </div>
    <div class="">
      <p style= "margin-top:1%;">Icon:</p>
      <%= r.text_field :icon %>
    </div>
    <div class="">
      <p style= "margin-top:1%;">Description:</p>
      <%= r.text_area :description, style: "width:80%; height:30vh;" %>
    </div>
    <%= r.submit "Save", style: "margin-top:1%" %>
  <% end %>
</div>

app/views/room/index.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
  </ol>

  <div class="welcomeImage" style="width:100%; height: 40vh;">
    <h1>The world evolves at the speed of tech.</h1>
    <h4>You and your business should, too.</h4>
    <div class="searchBar">
      <div id="sessionSearch" style="margin:3%;">
        <%= form_with url: search_path, id:"sessionSearch" do |form| %>
        <div class="input-group">
          <%= form.text_field(:search, class: 'search-query form-control', placeholder: "Search Topics") %>
          <div class="input-group-btn">
            <button class="btn btn-danger" type:'submit'><span class="glyphicon glyphicon-search"></span></button>
          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="indexBottom">
  <% @rooms.each do |room| %>
  <div class="sessionsRenderBox">
    <div class="panel panel-default">
      <%if current_user != nil && current_user.id.to_s === '1'%>
        <%= link_to edit_room_path(room, :id => room.id), controller: 'room', action: 'get', :class => "toolBTN float-right" do %>
          <span class="glyphicon glyphicon-pencil" title = "Edit room"> </span>
        <% end %>
        <%= link_to room_destroy_path(room, :id => room.id), controller: 'room', action: 'destroy', method: :delete, data: {confirm: 'Delete this room?'}, :class => "toolBTN float-right" do %>
          <span class="glyphicon glyphicon-trash" title = "Delete room"> </span>
        <% end %>
      <%end%>
      <%= link_to room_path(room.id) do %>
        <div class="panel-heading">:::<%= room.name %>:::</div>
      <% end %>
      <%room.topics.sort.reverse.take(6).each do |t|%>
        <%= link_to topic_path(t.id) do %>
          <div class="panel-footer">
            <%= t.title %>
            <p class="float-right" style="margin-right:2%;" title="Comments"><%= t.comments.length %></p>
            <p class="float-right glyphicon glyphicon-comment" style="margin-right:5px;" title="Comments"></p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <% end %>
  </div>

</div>

app/views/room/new.html.erb
<div class="container">
  <%if current_user != nil && current_user.id === 1%>
  <%= form_for @room do |f| %>
  <div>
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div>
    <%= f.text_area :description, placeholder: "description" %>
  </div>
  <%= f.submit %>
  <% end %>
  <%else%>
  <p>"User not allowed"</p>
  <%end%>
</div>

app/views/room/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to "#{@room.name}", room_path(@room.id) %></li>
  </ol>
  <div class="sessionHeaderBox">

    <div class="sessionHeader">
      <img class="sessionLogo" src='<%= @room.icon %>' alt="">

      <div class="sessionSearchBar">
        <span class="sessionName"><%= @room.name%></span>
        <div id="sessionSearch" style="margin-top:5%;">
          <%= form_with url: search_path do |form| %>
              <div class="input-group">
                <%= form.text_field(:search, class: 'search-query form-control', placeholder: "Search Topics") %>
              <div class="input-group-btn">
                <button class="btn btn-danger" type:'submit'><span class="glyphicon glyphicon-search"></span></button>
              </div>
            </div>
          <% end %>
          </div>
      </div>

    </div>

    <span class="helper"></span>

  </div>

  <div class="topicsContainer">
    <% @topics.reverse.each do |topic| %>
    <div class="topicBox">
      <%= link_to url_for(action: 'show', controller: 'topics', id: "#{topic.id}") do %>
        <h1 class="topicTitle"><%= topic.title %></h1>
      <% end %>
      <br>
      <p class="topicContent"><%= topic.content %></p>
        <p class="float-right">Created By:
          <%= link_to user_path(topic.owner_id) do %>
            <%= topic.owner_name %>
          <% end %>
        </p>
      <p class="float-right" style="margin-right:2%;" title="Comments"><%= topic.comments.length %></p>
      <p class="float-right glyphicon glyphicon-comment" style="margin-right:5px;" title="Comments"></p>
      <br>
      <%if topic.created_at === topic.updated_at%>
        <p class="float-right"><%= topic.created_at %></p>
      <%else%>
        <p class="float-right">Updated at: <%= topic.updated_at %></p>
      <%end%>
    </div>
    <% end %>
  </div>
  <% if current_user != nil%>
  <%= form_with scope: :topic, url: "topics" do |f| %>
    <div>
      <%= f.text_field :title, placeholder: "Title", style: "width:80%; opacity:.9; margin-top:3%;" %>
    </div>
    <div>
      <%= f.text_area :content, placeholder: "Content", style: "width:80%; height:30vh; opacity:.9;" %>
    </div>
    <div>
      <%= f.hidden_field :room_id, :value => "#{@room.id}"%>
    </div>

    <%= f.submit :class => " btn btn-default" %>
  <% end %>
  <% end %>

</div>