config/routes.rb
Rails.application.routes.draw do
  root to: 'room#index'

  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/topics', to: 'users#showtopics', as: 'user_topics'
  get '/users/:id/messages', to: 'users#showmessage', as: 'user_message'
  get '/users/:id/sendmessages', to: 'users#showsendmessage', as: 'user_message_send'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch "/users/:id", to: "users#update"

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  post '/search', to: 'search#search', as:'search'
  get '/search/:search', to: 'search#show', as: 'search_result'

  # get '/messages', to: 'message#index'
  post '/messages', to: 'message#create'
  patch '/users/:id/messages/destroy/send/:id', to: 'message#notshowsendmessage', as: 'message_notshow_send'
  patch '/users/:id/messages/destroy/receive/:id', to: 'message#notshowreceivemessage', as: 'message_notshow_receive'

  get '/rooms', to: 'room#index'
  get '/rooms/new', to: 'room#new'
  post '/rooms', to: 'room#create'
  get '/rooms/:id', to: 'room#show', as: 'room'
  get '/rooms/:id/edit', to: 'room#edit', as: 'edit_room'
  patch '/rooms/:id', to: 'room#update'
  delete '/rooms/destroy/:id', to: 'room#destroy', as: 'room_destroy'

  # get '/rooms/:id', to: 'topics#index'
  post '/rooms/:id', to: 'topics#create'
  get '/rooms/:id/topics/:id', to: 'topics#show', as: 'topic'
  get '/rooms/:id/topics/:id/edit', to: 'topics#edit', as: 'edit_topic'
  patch "/rooms/:id/topics/:id", to: "topics#update"
  delete '/rooms/:id/topics/destroy/:id', to: 'topics#destroy', as: 'topic_destroy'

  post '/rooms/:id/topics/:id', to: 'comments#create'
  get '/comments/:id', to: 'comments#show', as: 'comment'
  get '/comments/:id/edit', to: 'comments#edit', as: 'edit_comment'
  patch "/comments/:id", to: "comments#update"
  delete '/comments/destroy/:id', to: 'comments#destroy', as: 'comment_destroy'

end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true, length: {minimum: 3, maximum: 15}
  has_secure_password
  has_many :topics
  has_many :comments
  has_many :messages

  def self.confirm(params)
    @user = User.find_by({username: params[:username]})
    @user ? @user.authenticate(params[:password]) : false
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      login(@user)
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages.join(" ")
      render :new
    end
  end

  def edit
    @user = User.find_by_id(params[:id])
  end

  def update
    @user = User.find_by_id(params[:id])
    @user.update_attributes(params.require(:user).permit(:name, :email, :gender, :description))
    if @user.save
      redirect_to user_path(@user.id)
    end
  end


  def show
    @user = User.find_by_id(params[:id])
    @topics = @user.topics
    @message = Message.new
    # if (current_user != @user)
    #   flash[:error] = 'Stop Hacking!'
    #   redirect_to '/'
    # end
  end

  def showtopics
    @user = User.find_by_id(params[:id])
    @topics = @user.topics
    @message = Message.new
  end

  def showmessage
    @user = User.find_by_id(params[:id])
    @message = Message.new
    @receive_message = Message.where(:receiver_name => "#{@user.username}")
  end

  def showsendmessage
    @user = User.find_by_id(params[:id])
    @message = Message.new
    @send_message = Message.where(:sender_name => "#{@user.username}")
  end

  # def destroymessage
  #   @user = User.find_by_id(params[:id])
  #   @message = Message.find(params[:message_id])
  #   @user.messages.delete(@message)
  # end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
  </ol>
  <div class="profileContainer">
    <div class="profileHeader">
      <img src="<%= asset_path("gameIcon.png") %>" class="profileIcon"></img>
      <h1 class="profileName"><%= @user.username%> <span>--- Profile</span></h1>
    </div>

    <div class="profileBody">
      <div class="profileInfo">
        <%= form_for @user do |f| %>
          <div class="">
            <h1>Name:</h1>
            <%= f.text_field :name %>
          </div>
          <div class="">
            <p style= "margin-top:1%;">Email:</p>
            <%= f.text_field :email %>
          </div>
          <div class="">
            <p style= "margin-top:1%;">Gender:</p>
            <%= f.select :gender, ['Male','Female','Not sure'] %>
          </div>
          <div class="">
            <p style= "margin-top:1%;">Description:</p>
            <%= f.text_area :description %>
          </div>
          <%= f.submit "Save", style: "margin-top:1%" %>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="searchBar">
    <div id="custom-search-input">
          <div class="input-group">
              <input type="text" class="  search-query form-control" placeholder="Search" />
              <span class="input-group-btn">
                  <button class="btn btn-danger" type="button">
                      <span class=" glyphicon glyphicon-search"></span>
                  </button>
              </span>
          </div>
      </div>
  </div>

  <div class="welcomeImage" style="width:80%; margin: 3% auto;">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">

        <div class="item active">
          <img src='<%=image_path("welcome.jpg")%>' style="width:100%; height: 40vh;">
          <div class="carousel-caption">
          </div>
        </div>

        <div class="item">
          <img src='<%=image_path("welcome2.jpg")%>' style="width:100%; height: 40vh;">
          <div class="carousel-caption">
          </div>
        </div>

        <div class="item">
          <img src='<%=image_path("welcome3.jpg")%>' style="width:100%; height: 40vh;">
          <div class="carousel-caption">
          </div>
        </div>

      </div>

      <!-- Left and right controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </div>

  <div class="sessionsRenderBox">
    <%= link_to "This session", 'topics' %>

  </div>
  <div class="sessionsRenderBox">

  </div>
  <div class="sessionsRenderBox">

  </div>
  <div class="sessionsRenderBox">

  </div>

</div>

app/views/users/show.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
  </ol>
  <div class="profileContainer">
    <div class="profileHeader">
      <img src="<%= asset_path("gameIcon.png") %>" class="profileIcon"></img>
      <h1 class="profileName"><%= @user.username%> <span>--- Profile</span></h1>
      <% if current_user != nil%>
        <button class="btn btn-warning float-right" type="button" data-toggle="modal" data-target="#myModalMessage">Sent Message</button>
      <%end%>
      <% if current_user != nil && current_user.id.to_s === @user.id.to_s%>
        <%= button_to("Messages received", user_message_path, method: :get, :class => "btn btn-warning")%>
        <%= button_to("Messages send", user_message_send_path, method: :get, :class => "btn btn-warning")%>
      <% end %>
    </div>

    <div class="profileBody">
      <div class="profileInfo">
        <%if current_user != nil && current_user.id === @user.id%>
          <%= link_to edit_user_path(@user, :id => @user.id), controller: 'users', action: 'get' do %>
            <span class="glyphicon glyphicon-pencil" title = "Edit information"> </span>
          <% end %>
        <%end%>
        <p>Name: <%=@user.name%></p>
        <p>Email: <%=@user.email%></p>
        <p>Gender: <%=@user.gender%></p>
        <p>Created Topics: <%= link_to "#{@user.topics.length} topics", user_topics_path(@user.id) %> </p>
        <p>Description: <%=@user.description%></p>
      </div>
    </div>

  </div>
</div>

<!-- Modal for message -->
  <div class="modal fade" id="myModalMessage" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
      <!-- Modal Header -->
        <div class="modal-header">
            <button type="button" class="close"
               data-dismiss="modal">
                   <span aria-hidden="true">&times;</span>
                   <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title">
                Message
            </h4>
        </div>

        <!-- Modal Body -->
        <div class="modal-body">
            <%= form_for @message do |f| %>
            <p>Sent to:</p>
            <div>
              <%= f.text_field :receiver_name, placeholder: "receiver", :value => "#{@user.username}" %>
            </div>
            <div>
              <%= f.text_area :content, placeholder: "Content", style: "width:80%; height:20vh; margin-top:2%" %>
            </div>
            <%= f.submit "Sent", :class => "btn btn-default", style: "margin-top:2%"%>
            <%end%>
        </div>

        <!-- Modal Footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-default"
                    data-dismiss="modal">
                        Close
            </button>
        </div>
      </div>
    </div>
  </div>

app/views/users/showmessage.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to "#{@user.username}'s Profile", user_path(@user.id) %></li>
  </ol>
  <div class="profileContainer">
    <div class="profileHeader">
      <img src="<%= asset_path("gameIcon.png") %>" class="profileIcon"></img>
      <h1 class="profileName"><%= @user.username%> <span>--- Profile</span></h1>
      <% if current_user != nil%>
        <button class="btn btn-warning float-right" type="button" data-toggle="modal" data-target="#myModalMessage">Sent Message</button>
      <%end%>
      <% if current_user != nil && current_user.id.to_s === @user.id.to_s%>
        <%= button_to("Messages received", user_message_path, method: :get, :class => "btn btn-warning")%>
        <%= button_to("Messages send", user_message_send_path, method: :get, :class => "btn btn-warning")%>
      <% end %>
    </div>

    <div class="profileBody">
      <div class="profileInfo">
        <% @receive_message.each do |m|%>
          <% if m.receiver_show != nil%>
            <div class="messageBox" >
              <div class="messageShow" data-toggle="modal" data-target="#showMessage<%=m.id%>"><%=m.content%></div>
              <p class="lower-right">Send By: <%=m.sender_name%></p>
              <%= link_to message_notshow_receive_path(m, :id => m.id), controller: 'message', action: 'notshowreceivemessage', method: :patch, data: {confirm: 'Delete this message?'}, :class => "toolBTN float-right" do %>
                <span class="glyphicon glyphicon-trash" title = "Delete message"> </span>
              <% end %>
            </div>
            <!-- Modal for showmessage -->
            <div class="modal fade" id="showMessage<%=m.id%>" role="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <!-- Modal Header -->
                  <div class="modal-header">
                    <button type="button" class="close"
                    data-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                    <span class="sr-only">Close</span>
                  </button>
                  <h4 class="modal-title">
                    Send by: <%=m.sender_name%>
                  </h4>
                </div>

                <!-- Modal Body -->
                <div class="modal-body">
                  <p><%=m.content%><p>
                  </div>

                  <!-- Modal Footer -->
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default"
                    data-dismiss="modal">
                    Close
                  </button>
                </div>
              </div>
            </div>
          </div>
          <%end%>
        <%end%>
      </div>
    </div>

  </div>
</div>

<!-- Modal for message -->
  <div class="modal fade" id="myModalMessage" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
      <!-- Modal Header -->
        <div class="modal-header">
            <button type="button" class="close"
               data-dismiss="modal">
                   <span aria-hidden="true">&times;</span>
                   <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title">
                Message
            </h4>
        </div>

        <!-- Modal Body -->
        <div class="modal-body">
            <%= form_for @message do |f| %>
            <p>Sent to:</p>
            <div>
              <%= f.text_field :receiver_name, placeholder: "receiver", :value => "#{@user.username}" %>
            </div>
            <div>
              <%= f.text_area :content, placeholder: "Content", style: "width:80%; height:20vh; margin-top:2%" %>
            </div>
            <%= f.submit "Sent", :class => "btn btn-default", style: "margin-top:2%"%>
            <%end%>
        </div>

        <!-- Modal Footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-default"
                    data-dismiss="modal">
                        Close
            </button>
        </div>
      </div>
    </div>
  </div>

app/views/users/showsendmessage.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to "#{@user.username}'s Profile", user_path(@user.id) %></li>
  </ol>
  <div class="profileContainer">
    <div class="profileHeader">
      <img src="<%= asset_path("gameIcon.png") %>" class="profileIcon"></img>
      <h1 class="profileName"><%= @user.username%> <span>--- Profile</span></h1>
      <% if current_user != nil%>
        <button class="btn btn-warning float-right" type="button" data-toggle="modal" data-target="#myModalMessage">Sent Message</button>
      <%end%>
      <% if current_user != nil && current_user.id.to_s === @user.id.to_s%>
        <%= button_to("Messages received", user_message_path, method: :get, :class => "btn btn-warning")%>
        <%= button_to("Messages send", user_message_send_path, method: :get, :class => "btn btn-warning")%>
      <% end %>
    </div>

    <div class="profileBody">
      <div class="profileInfo">
        <% @send_message.each do |m|%>
         <% if m.sender_show != nil%>
          <div class="messageBox">
            <div class="messageShow" data-toggle="modal" data-target="#showMessage<%=m.id%>"><%=m.content%></div>
            <p class="lower-right">Send To: <%=m.receiver_name%></p>
            <%= link_to message_notshow_send_path(m, :id => m.id), controller: 'message', action: 'notshowsendmessage', method: :patch, data: {confirm: 'Delete this message?'}, :class => "toolBTN float-right" do %>
              <span class="glyphicon glyphicon-trash" title = "Delete message"> </span>
            <% end %>
          </div>
          <!-- Modal for showmessage -->
          <div class="modal fade" id="showMessage<%=m.id%>" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <!-- Modal Header -->
                <div class="modal-header">
                  <button type="button" class="close"
                  data-dismiss="modal">
                  <span aria-hidden="true">&times;</span>
                  <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">
                  Send to: <%=m.receiver_name%>
                </h4>
              </div>

              <!-- Modal Body -->
              <div class="modal-body">
                <p><%=m.content%><p>
                </div>

                <!-- Modal Footer -->
                <div class="modal-footer">
                  <button type="button" class="btn btn-default"
                  data-dismiss="modal">
                  Close
                </button>
              </div>
            </div>
          </div>
        </div>
         <%end%>
        <%end%>
      </div>
    </div>

  </div>
</div>

<!-- Modal for message -->
  <div class="modal fade" id="myModalMessage" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
      <!-- Modal Header -->
        <div class="modal-header">
            <button type="button" class="close"
               data-dismiss="modal">
                   <span aria-hidden="true">&times;</span>
                   <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title">
                Message
            </h4>
        </div>

        <!-- Modal Body -->
        <div class="modal-body">
            <%= form_for @message do |f| %>
            <p>Sent to:</p>
            <div>
              <%= f.text_field :receiver_name, placeholder: "receiver", :value => "#{@user.username}" %>
            </div>
            <div>
              <%= f.text_area :content, placeholder: "Content", style: "width:80%; height:20vh; margin-top:2%" %>
            </div>
            <%= f.submit "Sent", :class => "btn btn-default", style: "margin-top:2%"%>
            <%end%>
        </div>

        <!-- Modal Footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-default"
                    data-dismiss="modal">
                        Close
            </button>
        </div>
      </div>
    </div>
  </div>

app/views/users/showtopics.html.erb
<div class="container">
  <ol class="breadcrumb">
    <li><a href="/">Home</a></li>
    <li><%= link_to "#{@user.username}'s Profile", user_path(@user.id) %></li>
  </ol>
  <div class="profileContainer">
    <div class="profileHeader">
      <img src="<%= asset_path("gameIcon.png") %>" class="profileIcon"></img>
      <h1 class="profileName"><%= @user.username%> <span>--- Profile</span></h1>
      <% if current_user != nil%>
        <button class="btn btn-warning float-right" type="button" data-toggle="modal" data-target="#myModalMessage">Sent Message</button>
      <%end%>
      <% if current_user != nil && current_user.id.to_s === @user.id.to_s%>
        <%= button_to("Messages received", user_message_path, method: :get, :class => "btn btn-warning")%>
        <%= button_to("Messages send", user_message_send_path, method: :get, :class => "btn btn-warning")%>
      <% end %>
    </div>

    <div class="profileBody">
      <div class="profileInfo">
        <% @topics.reverse.each do |topic| %>
        <div class="topicBox">
          <%= link_to url_for(action: 'show', controller: 'topics', id: "#{topic.id}") do %>
            <h1 class="profileTopicTitle"><%= topic.title %></h1>
          <% end %>
          <br>
          <p class="topicContent"><%= topic.content %></p>
          <p class="float-right commentLine" style="margin-right:2%;" title="Comments"><%= topic.comments.length %> comments</p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Modal for message -->
  <div class="modal fade" id="myModalMessage" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
      <!-- Modal Header -->
        <div class="modal-header">
            <button type="button" class="close"
               data-dismiss="modal">
                   <span aria-hidden="true">&times;</span>
                   <span class="sr-only">Close</span>
            </button>
            <h4 class="modal-title">
                Message
            </h4>
        </div>

        <!-- Modal Body -->
        <div class="modal-body">
            <%= form_for @message do |f| %>
            <p>Sent to:</p>
            <div>
              <%= f.text_field :receiver_name, placeholder: "receiver", :value => "#{@user.username}" %>
            </div>
            <div>
              <%= f.text_area :content, placeholder: "Content", style: "width:80%; height:20vh; margin-top:2%" %>
            </div>
            <%= f.submit "Sent", :class => "btn btn-default", style: "margin-top:2%"%>
            <%end%>
        </div>

        <!-- Modal Footer -->
        <div class="modal-footer">
            <button type="button" class="btn btn-default"
                    data-dismiss="modal">
                        Close
            </button>
        </div>
      </div>
    </div>
  </div>