config/routes.rb
Rails.application.routes.draw do
  root to: 'room#index'

  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'
  get '/users/:id/topics', to: 'users#showtopics', as: 'user_topics'
  get '/users/:id/messages', to: 'users#showmessage', as: 'user_message'
  get '/users/:id/sendmessages', to: 'users#showsendmessage', as: 'user_message_send'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch "/users/:id", to: "users#update"

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

  post '/search', to: 'search#search', as:'search'
  get '/search/:search', to: 'search#show', as: 'search_result'

  # get '/messages', to: 'message#index'
  post '/messages', to: 'message#create'
  patch '/users/:id/messages/destroy/send/:id', to: 'message#notshowsendmessage', as: 'message_notshow_send'
  patch '/users/:id/messages/destroy/receive/:id', to: 'message#notshowreceivemessage', as: 'message_notshow_receive'

  get '/rooms', to: 'room#index'
  get '/rooms/new', to: 'room#new'
  post '/rooms', to: 'room#create'
  get '/rooms/:id', to: 'room#show', as: 'room'
  get '/rooms/:id/edit', to: 'room#edit', as: 'edit_room'
  patch '/rooms/:id', to: 'room#update'
  delete '/rooms/destroy/:id', to: 'room#destroy', as: 'room_destroy'

  # get '/rooms/:id', to: 'topics#index'
  post '/rooms/:id', to: 'topics#create'
  get '/rooms/:id/topics/:id', to: 'topics#show', as: 'topic'
  get '/rooms/:id/topics/:id/edit', to: 'topics#edit', as: 'edit_topic'
  patch "/rooms/:id/topics/:id", to: "topics#update"
  delete '/rooms/:id/topics/destroy/:id', to: 'topics#destroy', as: 'topic_destroy'

  post '/rooms/:id/topics/:id', to: 'comments#create'
  get '/comments/:id', to: 'comments#show', as: 'comment'
  get '/comments/:id/edit', to: 'comments#edit', as: 'edit_comment'
  patch "/comments/:id", to: "comments#update"
  delete '/comments/destroy/:id', to: 'comments#destroy', as: 'comment_destroy'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3</title>
    <%= csrf_meta_tags %>

    <script src="https://code.jquery.com/jquery-3.2.1.js" ></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
    <div class="headerLogo">
      <a href="/"><img class="mainLogo" src="<%= asset_path("galogo.png") %>"></a>
    </div>

    <div class="userSession">
        <% if current_user %>
          <%= button_to("Log out", logout_path, method: :get, :class => "btn btn-default logBtn", form_class: "logBtn")%>
          <%= button_to("Profile", user_path(current_user), method: :get, :class => "btn btn-default logBtn", form_class: "logBtn") %>
          <%= button_to("Home", '/', method: :get, :class => " btn btn-default logBtn", form_class: "logBtn") %>
        <% else %>
        <button class="btn btn-default logBtn" type="button" name="signup" data-toggle="modal" data-target="#myModalSignUp">Sign Up</button>
        <button class="btn btn-default logBtn" type="button" name="signin" data-toggle="modal" data-target="#myModalSignIn">Sign In</button>
        <%= button_to("Home", '/', method: :get, :class => " btn btn-default logBtn", form_class: "logBtn") %>
        <% end %>
    </div>
  </header>
    <% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
        <%= value %>
      </div>
    <% end %>

    <img src='<%=image_path("banner.png")%>' class="banner" style="margin-bottom: 1.5%">

    <%= yield %>

    <footer>
      <p>GA Project | 225 Bush St, San Francisco, CA 94104 | By: Ken</p>
    </footer>

    <!-- Modal for sign in -->
    <div class="modal fade" id="myModalSignIn" role="dialog">
      <div class="modal-dialog">
        <div class="modal-content">
        <!-- Modal Header -->
          <div class="modal-header">
              <button type="button" class="close"
                 data-dismiss="modal">
                     <span aria-hidden="true">&times;</span>
                     <span class="sr-only">Close</span>
              </button>
              <h4 class="modal-title" id="myModalLabel">
                  Sign In
              </h4>
          </div>

          <!-- Modal Body -->
          <div class="modal-body">
              <%= form_for @user, url: "/sessions", method: "post" do |f| %>
              <div>
                <%= f.text_field :username, placeholder: "Username" %>
              </div>
              <div>
                <%= f.password_field :password, placeholder: "Password", style: "margin-top:2%" %>
              </div>
              <%= f.submit "Log In", :class => "btn btn-default", style: "margin-top:2%"%>
              <%end%>
          </div>

          <!-- Modal Footer -->
          <div class="modal-footer">
              <button type="button" class="btn btn-default"
                      data-dismiss="modal">
                          Close
              </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Modal for sign up -->
      <div class="modal fade" id="myModalSignUp" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
          <!-- Modal Header -->
            <div class="modal-header">
                <button type="button" class="close"
                   data-dismiss="modal">
                       <span aria-hidden="true">&times;</span>
                       <span class="sr-only">Close</span>
                </button>
                <h4 class="modal-title">
                    Sign Up Form
                </h4>
            </div>

            <!-- Modal Body -->
            <div class="modal-body">
                <%= form_for @user do |f| %>
                <div>
                  <%= f.text_field :username, placeholder: "UserName" %>
                </div>
                <div>
                  <%= f.password_field :password, placeholder: "Password", style: "margin-top:2%" %>
                </div>
                <%= f.submit "Sign up", :class => "btn btn-default", style: "margin-top:2%" %>
                <%end%>
            </div>

            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                            Close
                </button>
            </div>
          </div>
        </div>
      </div>
  </body>
</html>